[package]
name = "cw-stake-tracker"
version = "2.1.0"
edition = "2021"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "A package for tracking staked and unbonding tokens in x/staking."
license = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace =  true }
cw-wormhole = { workspace = true }
